version: '3.9'
services:
  server:
    container_name: server
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=production
    command: "pnpm start"
