FROM node:14-alpine

WORKDIR /usr/src/app

RUN npm i -g pnpm

COPY ./.npmrc ./
COPY ./package.json ./
COPY ./pnpm-lock.yaml ./

ENV NODE_ENV=development

RUN pnpm install

COPY ./ ./

EXPOSE 3000

CMD ["pnpm", "start:dev"]
