version: '3.9'
services:
  server:
    container_name: server
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - .env
    restart: always
  db:
    container_name: db
    image: mysql
    command: --authentication-policy=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/mysql
  redis:
    container_name: redis
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - .env
